// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"payment-service/internal/modules/category/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// CategoryRepository abstract interface
type CategoryRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterCategory) ([]shareddomain.PaymentCategory, error)
	Count(ctx context.Context, filter *domain.FilterCategory) int
	Find(ctx context.Context, filter *domain.FilterCategory) (shareddomain.PaymentCategory, error)
	Save(ctx context.Context, data *shareddomain.PaymentCategory, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterCategory) (err error)
}
