// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"monorepo/services/user-service/internal/modules/driver/domain"
	shareddomain "monorepo/services/user-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// DriverRepository abstract interface
type DriverRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterDriver) ([]shareddomain.Driver, error)
	Count(ctx context.Context, filter *domain.FilterDriver) int
	Find(ctx context.Context, filter *domain.FilterDriver) (shareddomain.Driver, error)
	Save(ctx context.Context, data *shareddomain.Driver, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterDriver) (err error)
}
