// Code generated by candi v1.18.8.

package resthandler

import (
	"net/http"
	"strconv"

	"payment-service/internal/modules/checkout/domain"
	"payment-service/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Checkout := root.Group(candihelper.V1+"/checkout", h.mw.HTTPBearerAuth)

	v1Checkout.GET("/methodlist", h.getMethodList)
	// v1Checkout.POST("/pay", h.getMethodList)
}

func (h *RestHandler) getMethodList(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "CategoryDeliveryREST:GetAllCategory")
	defer trace.Finish()

	var filter domain.FilterCheckout
	if err := candihelper.ParseFromQueryParam(req.URL.Query(), &filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(rw)
		return
	}

	if err := h.validator.ValidateDocument("category/get_all", filter); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(rw)
		return
	}

	result, err := h.uc.Checkout().GetListMethod(ctx, &filter)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	message := "Success get all method, page " + strconv.Itoa(filter.Page) + " with " + strconv.Itoa(len(result.Data)) + " data"
	response := wrapper.NewHTTPResponse(http.StatusOK, message, result.Data)
	response.Meta = result.Meta
	response.JSON(rw)
}

// func (h *RestHandler) payCheckout(rw http.ResponseWriter, req *http.Request) {
// 	trace, ctx := tracer.StartTraceWithContext(req.Context(), "CheckoutDeliveryREST:PayCheckout")
// 	defer trace.Finish()

// 	body, _ := io.ReadAll(req.Body)
// 	if err := h.validator.ValidateDocument("checkout/pay", body); err != nil {
// 		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
// 		return
// 	}

// 	var payload domain.RequestPayCheckout
// 	if err := json.Unmarshal(body, &payload); err != nil {
// 		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
// 		return
// 	}

// 	res, err := h.uc.Checkout().PayCheckout(ctx, &payload)
// 	if err != nil {
// 		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
// 		return
// 	}

// 	wrapper.NewHTTPResponse(http.StatusOK, "Success", res).JSON(rw)
// }
