// Code generated by candi v1.18.8.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"

	"monorepo/services/user-service/internal/modules/auth/domain"
	"monorepo/services/user-service/pkg/helper"
	"monorepo/services/user-service/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Auth := root.Group(candihelper.V1 + "/auth")

	v1Auth.POST("/login", h.login)
	v1Auth.POST("/logout", h.logout, h.mw.HTTPBearerAuth)
	v1Auth.POST("/token/verify", h.verifyToken)
	v1Auth.POST("/token/refresh", h.refresh)
}

func (h *RestHandler) login(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "AuthDeliveryREST:Login")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("auth/login", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	var payload domain.LoginPayload
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	resp, err := h.uc.Auth().Login(ctx, payload.Email, payload.Password)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Login", resp).JSON(rw)
}

func (h *RestHandler) logout(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "AuthDeliveryREST:Logout")
	defer trace.Finish()
	ctx = trace.Context()

	token, err := helper.ExtractBearerToken(req)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	err = h.uc.Auth().Logout(ctx, token)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Logout", nil).JSON(rw)
}

func (h *RestHandler) verifyToken(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "UserGroupDeliveryREST:Verify")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("auth/verify_token", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed verify payload", err).JSON(rw)
		return
	}

	var payload domain.VerifyTokenPayload
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	data, err := h.uc.Auth().ValidateToken(ctx, payload.Token)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Verify Token", data).JSON(rw)
}

func (h *RestHandler) refresh(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "AuthDeliveryREST:RefreshToken")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("auth/refresh_token", body); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	var payload domain.RefreshTokenPayload
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	data, err := h.uc.Auth().RefreshToken(ctx, "", payload.RefreshToken)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Refresh Token", data).JSON(rw)
}
