// Code generated by candi v1.18.8.

package configs

import (
	"context"
	"crypto/rand"
	"crypto/rsa"

	"monorepo/sdk"
	"monorepo/services/user-service/api"
	"monorepo/services/user-service/pkg/shared"
	"monorepo/services/user-service/pkg/shared/repository"
	"monorepo/services/user-service/pkg/shared/usecase"

	"github.com/golangid/candi/broker"
	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/candiutils"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/config"
	"github.com/golangid/candi/config/database"

	"github.com/golangid/candi/logger"
	"github.com/golangid/candi/middleware"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/validator"
)

// devRSAKey is a simple RSA key holder used for local development to
// satisfy the candi interfaces.RSAKey requirements (PublicKey/PrivateKey).
// Declared at package level because method declarations cannot be inside
// function scope.
type devRSAKey struct{ priv *rsa.PrivateKey }

func (d *devRSAKey) PublicKey() *rsa.PublicKey   { return &d.priv.PublicKey }
func (d *devRSAKey) PrivateKey() *rsa.PrivateKey { return d.priv }

// LoadServiceConfigs load selected dependency configuration in this service
func LoadServiceConfigs(baseCfg *config.Config) (deps dependency.Dependency) {
	var sharedEnv shared.Environment
	candihelper.MustParseEnv(&sharedEnv)
	shared.SetEnv(sharedEnv)

	logger.InitZap()
	// logger.SetMaskLog(logger.NewMasker()) // add this for mask sensitive information

	baseCfg.LoadFunc(func(ctx context.Context) []interfaces.Closer {
		jaeger := tracer.InitJaeger(baseCfg.ServiceName)
		redisDeps := database.InitRedis()
		sqlDeps := database.InitSQLDatabase()
		// mongoDeps := database.InitMongoDB(ctx)

		// generate a dev RSA key for local RS256 validation (local/dev only)
		rsaKey, _ := rsa.GenerateKey(rand.Reader, 2048)

		sdk.SetGlobalSDK(
		// init service client sdk
		)

		locker := &candiutils.NoopLocker{}

		brokerDeps := broker.InitBrokers(
			// broker.NewKafkaBroker(),
			// broker.NewRabbitMQBroker(),
			broker.NewRedisBroker(redisDeps.WritePool()),
		)

		validatorDeps := validator.NewValidator()
		validatorDeps.JSONSchema.SchemaStorage = validator.NewFileSystemStorage(api.JSONSchema, "jsonschema")

		// inject all service dependencies
		// See all option in dependency package
		deps = dependency.InitDependency(
			dependency.SetValidator(validatorDeps),
			dependency.SetBrokers(brokerDeps.GetBrokers()),
			dependency.SetLocker(locker),
			dependency.SetRedisPool(redisDeps),
			dependency.SetSQLDatabase(sqlDeps),
			// register dev RSA key (for local RS256 validation)
			dependency.SetKey(&devRSAKey{priv: rsaKey}),
			// dependency.SetMongoDatabase(mongoDeps),
			// ... add more dependencies
		)
		return []interfaces.Closer{ // throw back to base config for close connection when application shutdown
			jaeger, deps,
		}
	})

	repository.SetSharedRepository(deps)
	usecase.SetSharedUsecase(deps)

	deps.SetMiddleware(middleware.NewMiddlewareWithOption(
		middleware.SetTokenValidator(&shared.DefaultMiddleware{}),
		// middleware.SetACLPermissionChecker(&shared.DefaultMiddleware{}),
		middleware.SetUserIDExtractor(func(tokenClaim *candishared.TokenClaim) (userID string) {
			return tokenClaim.Subject
		}),
		middleware.SetCache(deps.GetRedisPool().Cache(), middleware.DefaultCacheAge),
	))

	return deps
}
