// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"monorepo/services/user-service/internal/modules/mitra/domain"
	shareddomain "monorepo/services/user-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// MitraRepository abstract interface
type MitraRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterMitra) ([]shareddomain.Mitra, error)
	Count(ctx context.Context, filter *domain.FilterMitra) int
	Find(ctx context.Context, filter *domain.FilterMitra) (shareddomain.Mitra, error)
	Save(ctx context.Context, data *shareddomain.Mitra, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterMitra) (err error)
}
