// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"strings"
	"time"

	"payment-service/internal/modules/checkout/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"payment-service/pkg/shared"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type checkoutRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewCheckoutRepoSQL mongo repo constructor
func NewCheckoutRepoSQL(readDB, writeDB *gorm.DB) CheckoutRepository {
	return &checkoutRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *checkoutRepoSQL) FetchMethodGroupByCategory(ctx context.Context, filter *domain.FilterCheckout) (data []shareddomain.PaymentCategory, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CheckoutRepoSQL:FetchMethodGroupByCategory")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "sequence"
	}

	db := r.setFilterCheckout(shared.SetSpanToGorm(ctx, r.readDB), filter).Where("is_active = ?", true).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "ASC",
	})
	db = db.Where("is_active = ?", true)
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}

	// Preload Method dan terapkan kondisi WHERE hanya pada method yang di-preload
	db = db.Preload("Method", "is_active = ?", true)

	err = db.Find(&data).Error
	return
}

func (r *checkoutRepoSQL) CountMethod(ctx context.Context, filter *domain.FilterCheckout) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CheckoutRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterCheckout(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.PaymentMethod{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *checkoutRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterCheckout) (data []shareddomain.Checkout, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CheckoutRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterCheckout(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *checkoutRepoSQL) Count(ctx context.Context, filter *domain.FilterCheckout) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CheckoutRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterCheckout(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Checkout{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *checkoutRepoSQL) Find(ctx context.Context, filter *domain.FilterCheckout) (result shareddomain.Checkout, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CheckoutRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterCheckout(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *checkoutRepoSQL) Save(ctx context.Context, data *shareddomain.Checkout, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CheckoutRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = shared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *checkoutRepoSQL) Delete(ctx context.Context, filter *domain.FilterCheckout) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CheckoutRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterCheckout(shared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Checkout{}).Error
	return
}

func (r *checkoutRepoSQL) setFilterCheckout(db *gorm.DB, filter *domain.FilterCheckout) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
