// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"payment-service/internal/modules/checkout/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// CheckoutRepository abstract interface
type CheckoutRepository interface {
	FetchMethodGroupByCategory(ctx context.Context, filter *domain.FilterCheckout) ([]shareddomain.PaymentCategory, error)
	CountMethod(ctx context.Context, filter *domain.FilterCheckout) int
	FetchAll(ctx context.Context, filter *domain.FilterCheckout) ([]shareddomain.Checkout, error)
	Count(ctx context.Context, filter *domain.FilterCheckout) int
	Find(ctx context.Context, filter *domain.FilterCheckout) (shareddomain.Checkout, error)
	Save(ctx context.Context, data *shareddomain.Checkout, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterCheckout) (err error)
}
