// Code generated by candi v1.18.8.

package main

import (
	"fmt"
	"runtime/debug"

	_ "github.com/lib/pq"

	"github.com/golangid/candi/codebase/app"
	"github.com/golangid/candi/config"

	service "payment-service/internal"
	pkg_midtrans "payment-service/pkg/helper/midtrans"
)

func main() {
	const serviceName = "payment-service"

	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("\x1b[31;1mFailed to start %s service: %v\x1b[0m\n", serviceName, r)
			fmt.Printf("Stack trace: \n%s\n", debug.Stack())
		}
	}()

	pkg_midtrans.Init()
	cfg := config.Init(serviceName)
	defer cfg.Exit()

	app.New(service.NewService(cfg)).Run()
}
