// Code generated by candi v1.18.8.

package usecase

import (
	"monorepo/services/user-service/pkg/shared/repository"
	"monorepo/services/user-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// MitraUsecase abstraction
type MitraUsecase interface {
}

type mitraUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewMitraUsecase usecase impl constructor
func NewMitraUsecase(deps dependency.Dependency) (MitraUsecase, func(sharedUsecase common.Usecase)) {
	uc := &mitraUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),

	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
