// Code generated by candi v1.18.8.

package usecase

import (
	"context"

	"payment-service/internal/modules/method/domain"
	"payment-service/pkg/shared/repository"
	"payment-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// MethodUsecase abstraction
type MethodUsecase interface {
	GetAllMethod(ctx context.Context, filter *domain.FilterMethod) (data domain.ResponseMethodList, err error)
	GetDetailMethod(ctx context.Context, id int) (data domain.ResponseMethod, err error)
	CreateMethod(ctx context.Context, data *domain.RequestMethod) (res domain.ResponseMethod, err error) 
	UpdateMethod(ctx context.Context, data *domain.RequestMethod) (err error)
	DeleteMethod(ctx context.Context, id int) (err error)
}

type methodUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewMethodUsecase usecase impl constructor
func NewMethodUsecase(deps dependency.Dependency) (MethodUsecase, func(sharedUsecase common.Usecase)) {
	uc := &methodUsecaseImpl{
		deps:    deps,
		repoSQL:   repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
		
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
