// Code generated by candi v1.18.8.

package usecase

import (
	"context"
	"payment-service/internal/modules/payment/domain"
	"payment-service/pkg/shared/repository"
	"payment-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// PaymentUsecase abstraction
type PaymentUsecase interface {
	// GetAllPayment(ctx context.Context, filter *domain.FilterPayment) (data domain.ResponsePaymentList, err error)
	// GetDetailPayment(ctx context.Context, id int) (data domain.ResponsePayment, err error)
	// CreatePayment(ctx context.Context, data *domain.RequestPayment) (res domain.ResponsePayment, err error)
	// UpdatePayment(ctx context.Context, data *domain.RequestPayment) (err error)
	// DeletePayment(ctx context.Context, id int) (err error)
	CreateTransaction(ctx context.Context, req *domain.CreateOrderRequest) (*domain.CreateTransactionResponse, error)
}

type paymentUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewPaymentUsecase usecase impl constructor
func NewPaymentUsecase(deps dependency.Dependency) (PaymentUsecase, func(sharedUsecase common.Usecase)) {
	uc := &paymentUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),

	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
