// Code generated by candi v1.18.8.

package usecase

import (
	"context"
	"payment-service/internal/modules/payment/domain"
	"payment-service/pkg/shared/repository"
	"payment-service/pkg/shared/service"
	"payment-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// PaymentUsecase abstraction
type PaymentUsecase interface {
	CreateTransaction(ctx context.Context, req *domain.CreateOrderRequest) (*domain.CreateTransactionResponse, error)
	HandleMidtransNotification(ctx context.Context, notif domain.MidtransNotification) error
}

type paymentUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	service       service.Service
	// repoMongo     repository.RepoMongo
}

// NewPaymentUsecase usecase impl constructor
func NewPaymentUsecase(deps dependency.Dependency) (PaymentUsecase, func(sharedUsecase common.Usecase)) {
	uc := &paymentUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		service: deps.GetExtended(service.KeyExternalService).(service.Service),
		// repoMongo: repository.GetSharedRepoMongo(),
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
