// Code generated by candi v1.18.8.

package usecase

import (
	"context"

	"monorepo/services/order-service/internal/modules/order/domain"
	"monorepo/services/order-service/pkg/shared/repository"
	"monorepo/services/order-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// OrderUsecase abstraction
type OrderUsecase interface {
	GetAllOrder(ctx context.Context, filter *domain.FilterOrder) (data domain.ResponseOrderList, err error)
	GetDetailOrder(ctx context.Context, id int) (data domain.ResponseOrder, err error)
	CreateOrder(ctx context.Context, data *domain.RequestOrder) (res domain.ResponseOrder, err error) 
	UpdateOrder(ctx context.Context, data *domain.RequestOrder) (err error)
	DeleteOrder(ctx context.Context, id int) (err error)
}

type orderUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewOrderUsecase usecase impl constructor
func NewOrderUsecase(deps dependency.Dependency) (OrderUsecase, func(sharedUsecase common.Usecase)) {
	uc := &orderUsecaseImpl{
		deps:    deps,
		repoSQL:   repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
		
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
