// Code generated by candi v1.18.8.

package usecase

import (
	"monorepo/services/user-service/pkg/shared/repository"
	"monorepo/services/user-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// DriverUsecase abstraction
type DriverUsecase interface {
}

type driverUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewDriverUsecase usecase impl constructor
func NewDriverUsecase(deps dependency.Dependency) (DriverUsecase, func(sharedUsecase common.Usecase)) {
	uc := &driverUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),

	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
