// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"monorepo/services/order-service/internal/modules/order/domain"
	shareddomain "monorepo/services/order-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// OrderRepository abstract interface
type OrderRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterOrder) ([]shareddomain.Order, error)
	Count(ctx context.Context, filter *domain.FilterOrder) int
	Find(ctx context.Context, filter *domain.FilterOrder) (shareddomain.Order, error)
	Save(ctx context.Context, data *shareddomain.Order, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterOrder) (err error)
}
