// Code generated by candi v1.18.8.

package repository

import (
	"context"
	
	"time"
	"strings"

	"monorepo/services/order-service/internal/modules/order/domain"
	shareddomain "monorepo/services/order-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"monorepo/globalshared"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type orderRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewOrderRepoSQL mongo repo constructor
func NewOrderRepoSQL(readDB, writeDB *gorm.DB) OrderRepository {
	return &orderRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *orderRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterOrder) (data []shareddomain.Order, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "OrderRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterOrder(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *orderRepoSQL) Count(ctx context.Context, filter *domain.FilterOrder) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "OrderRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterOrder(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Order{}).Count(&total)
	count = int(total)
	
	trace.Log("count", count)
	return
}

func (r *orderRepoSQL) Find(ctx context.Context, filter *domain.FilterOrder) (result shareddomain.Order, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "OrderRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterOrder(globalshared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *orderRepoSQL) Save(ctx context.Context, data *shareddomain.Order, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "OrderRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = globalshared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = globalshared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *orderRepoSQL) Delete(ctx context.Context, filter *domain.FilterOrder) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "OrderRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterOrder(globalshared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Order{}).Error
	return
}

func (r *orderRepoSQL) setFilterOrder(db *gorm.DB, filter *domain.FilterOrder) *gorm.DB {
	
	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
