// Code generated by candi v1.18.8.

package repository

import (
	"context"
	"payment-service/internal/modules/payment/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"

	"gorm.io/gorm"
)

type paymentRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewPaymentRepoSQL mongo repo constructor
func NewPaymentRepoSQL(readDB, writeDB *gorm.DB) PaymentRepository {
	return &paymentRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *paymentRepoSQL) setFilterPayment(db *gorm.DB, filter *domain.FilterPayment) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}

func (r *paymentRepoSQL) Save(ctx context.Context, data *shareddomain.PaymentOrder) error {
	return r.writeDB.WithContext(ctx).Save(data).Error
}
