// Code generated by candi v1.18.8.

package repository

import (
	"context"
	"payment-service/internal/modules/payment/domain"
	shareddomain "payment-service/pkg/shared/domain"
	"time"

	"github.com/golangid/candi/candishared"

	"gorm.io/gorm"
)

type paymentRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewPaymentRepoSQL mongo repo constructor
func NewPaymentRepoSQL(readDB, writeDB *gorm.DB) PaymentRepository {
	return &paymentRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *paymentRepoSQL) setFilterPayment(db *gorm.DB, filter *domain.FilterPayment) *gorm.DB {
	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}

func (r *paymentRepoSQL) Save(ctx context.Context, data *shareddomain.PaymentOrder) error {
	return r.writeDB.WithContext(ctx).Save(data).Error
}

func (r *paymentRepoSQL) FindByOrderID(ctx context.Context, orderID string) (*shareddomain.PaymentOrder, error) {
	var paymentOrder shareddomain.PaymentOrder

	err := r.readDB.WithContext(ctx).Where("order_id", orderID).First(&paymentOrder).Error
	return &paymentOrder, err
}

func (r *paymentRepoSQL) SaveLog(ctx context.Context, log *shareddomain.PaymentLog, methodID int) error {
	log.CreatedAt = time.Now()
	_ = r.readDB.Table("payment_method").
		Select("payment_method.provider_id").
		Where("payment_method.id = ?", methodID).Scan(&log.ProviderID)

	return r.writeDB.WithContext(ctx).Create(log).Error
}
