// Code generated by candi v1.18.8.

package shared

// Environment additional in this service
type Environment struct {
	// more additional environment with struct tag is environment key example:
	// ExampleHost string `env:"EXAMPLE_HOST"`
	MidtransEnv        string `env:"MIDTRANS_ENV"`
	MidtransMerchantID string `env:"MIDTRANS_MERCHANT_ID"`
	MidtransServerKey  string `env:"MIDTRANS_SERVER_KEY"`
	MidtransClientKey  string `env:"MIDTRANS_CLIENT_KEY"`
	UserServiceHost    string `env:"USER_SERVICE_HOST"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
