// Code generated by candi v1.18.8.

package shared

// this file only for example

import (
	"context"
	"fmt"

	"monorepo/sdk"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/logger"
)

var (
	ErrTokenInvalid = fmt.Errorf("Token is not valid")
)

type DefaultMiddleware interface {
	ValidateToken(ctx context.Context, token string) (*candishared.TokenClaim, error)
	CheckPermission(ctx context.Context, userID string, permissionCode string) (role string, err error)
}

// DefaultMiddleware for middleware validator example
type DefaultMiddlewareImpl struct {
	sdk sdk.SDK
}

func NewDefaultMiddleware() DefaultMiddleware {
	return &DefaultMiddlewareImpl{
		sdk: sdk.GetSDK(),
	}
}

// ValidateToken implement TokenValidator
func (d DefaultMiddlewareImpl) ValidateToken(ctx context.Context, token string) (*candishared.TokenClaim, error) {
	_, err := d.sdk.Userservice().VerifyToken(ctx, token)
	if err != nil {
		return nil, ErrTokenInvalid
	}

	var tokenClaim candishared.TokenClaim
	tokenClaim.Subject = "USER_ID"

	logger.LogI("validate token: allowed")
	return &tokenClaim, nil
}

// CheckPermission implement interfaces.ACLPermissionChecker
func (d DefaultMiddlewareImpl) CheckPermission(ctx context.Context, userID string, permissionCode string) (role string, err error) {
	/* add check allow permission for user access (is given "userID" can access "permissionCode" ?)
	if !contains(getAllPermissionFromUser(userID), permissionCode) {
		return role, errors.New("Forbidden")
	}
	*/
	logger.LogIf("check permission: users with id '%s' can access resource with permission code '%s' (return role for this user is 'superadmin')", userID, permissionCode)
	return "superadmin", nil
}
