// Code generated by candi v1.18.8.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	bankusecase "payment-service/internal/modules/bank/usecase"
	categoryusecase "payment-service/internal/modules/category/usecase"
	methodusecase "payment-service/internal/modules/method/usecase"
	providerusecase "payment-service/internal/modules/provider/usecase"
	"payment-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Provider() providerusecase.ProviderUsecase
		Method() methodusecase.MethodUsecase
		Category() categoryusecase.CategoryUsecase
		Bank() bankusecase.BankUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		providerusecase.ProviderUsecase
		methodusecase.MethodUsecase
		categoryusecase.CategoryUsecase
		bankusecase.BankUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.ProviderUsecase, setSharedUsecaseFunc = providerusecase.NewProviderUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.MethodUsecase, setSharedUsecaseFunc = methodusecase.NewMethodUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.CategoryUsecase, setSharedUsecaseFunc = categoryusecase.NewCategoryUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.BankUsecase, setSharedUsecaseFunc = bankusecase.NewBankUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Provider() providerusecase.ProviderUsecase {
	return uc.ProviderUsecase
}

func (uc *usecaseUow) Method() methodusecase.MethodUsecase {
	return uc.MethodUsecase
}

func (uc *usecaseUow) Category() categoryusecase.CategoryUsecase {
	return uc.CategoryUsecase
}

func (uc *usecaseUow) Bank() bankusecase.BankUsecase {
	return uc.BankUsecase
}
