// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"strings"
	"time"

	"monorepo/services/user-service/internal/modules/user/domain"
	shareddomain "monorepo/services/user-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"monorepo/globalshared"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type userRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewUserRepoSQL mongo repo constructor
func NewUserRepoSQL(readDB, writeDB *gorm.DB) UserRepository {
	return &userRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *userRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterUser) (data []shareddomain.User, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterUser(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *userRepoSQL) Count(ctx context.Context, filter *domain.FilterUser) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterUser(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.User{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *userRepoSQL) Find(ctx context.Context, filter *domain.FilterUser) (result shareddomain.User, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterUser(globalshared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *userRepoSQL) Save(ctx context.Context, data *shareddomain.User, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = globalshared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = globalshared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *userRepoSQL) Delete(ctx context.Context, filter *domain.FilterUser) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "UserRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterUser(globalshared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.User{}).Error
	return
}

func (r *userRepoSQL) setFilterUser(db *gorm.DB, filter *domain.FilterUser) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}

	if filter.Email != nil {
		db = db.Where("email = ?", *filter.Email)
	}

	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
