// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"strings"
	"time"

	"payment-service/internal/modules/bank/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"payment-service/pkg/shared"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type bankRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewBankRepoSQL mongo repo constructor
func NewBankRepoSQL(readDB, writeDB *gorm.DB) BankRepository {
	return &bankRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *bankRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterBank) (data []shareddomain.PaymentBank, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BankRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterBank(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *bankRepoSQL) Count(ctx context.Context, filter *domain.FilterBank) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BankRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterBank(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.PaymentBank{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *bankRepoSQL) Find(ctx context.Context, filter *domain.FilterBank) (result shareddomain.PaymentBank, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BankRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterBank(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *bankRepoSQL) Save(ctx context.Context, data *shareddomain.PaymentBank, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BankRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = shared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *bankRepoSQL) Delete(ctx context.Context, filter *domain.FilterBank) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BankRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterBank(shared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.PaymentBank{}).Error
	return
}

func (r *bankRepoSQL) setFilterBank(db *gorm.DB, filter *domain.FilterBank) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(name ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
