// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"payment-service/internal/modules/bank/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// BankRepository abstract interface
type BankRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterBank) ([]shareddomain.PaymentBank, error)
	Count(ctx context.Context, filter *domain.FilterBank) int
	Find(ctx context.Context, filter *domain.FilterBank) (shareddomain.PaymentBank, error)
	Save(ctx context.Context, data *shareddomain.PaymentBank, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterBank) (err error)
}
