// Code generated by candi v1.18.8.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	authusecase "monorepo/services/user-service/internal/modules/auth/usecase"
	driverusecase "monorepo/services/user-service/internal/modules/driver/usecase"
	mitrausecase "monorepo/services/user-service/internal/modules/mitra/usecase"
	userusecase "monorepo/services/user-service/internal/modules/user/usecase"
	"monorepo/services/user-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		User() userusecase.UserUsecase
		Mitra() mitrausecase.MitraUsecase
		Driver() driverusecase.DriverUsecase
		Auth() authusecase.AuthUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		userusecase.UserUsecase
		mitrausecase.MitraUsecase
		driverusecase.DriverUsecase
		authusecase.AuthUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.UserUsecase, setSharedUsecaseFunc = userusecase.NewUserUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.MitraUsecase, setSharedUsecaseFunc = mitrausecase.NewMitraUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.DriverUsecase, setSharedUsecaseFunc = driverusecase.NewDriverUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.AuthUsecase, setSharedUsecaseFunc = authusecase.NewAuthUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) User() userusecase.UserUsecase {
	return uc.UserUsecase
}

func (uc *usecaseUow) Mitra() mitrausecase.MitraUsecase {
	return uc.MitraUsecase
}

func (uc *usecaseUow) Driver() driverusecase.DriverUsecase {
	return uc.DriverUsecase
}

func (uc *usecaseUow) Auth() authusecase.AuthUsecase {
	return uc.AuthUsecase
}
