// Code generated by candi v1.18.8.

package usecase

import (
	"context"

	"payment-service/internal/modules/checkout/domain"
	"payment-service/pkg/shared/repository"
	"payment-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// CheckoutUsecase abstraction
type CheckoutUsecase interface {
	GetListMethod(ctx context.Context, filter *domain.FilterCheckout) (data domain.ResponseMethodList, err error)
}

type checkoutUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewCheckoutUsecase usecase impl constructor
func NewCheckoutUsecase(deps dependency.Dependency) (CheckoutUsecase, func(sharedUsecase common.Usecase)) {
	uc := &checkoutUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),

	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
