// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"monorepo/services/user-service/internal/modules/auth/domain"
	shareddomain "monorepo/services/user-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// AuthRepository abstract interface
type AuthRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterAuth) ([]shareddomain.Auth, error)
	Count(ctx context.Context, filter *domain.FilterAuth) int
	Find(ctx context.Context, filter *domain.FilterAuth) (shareddomain.Auth, error)
	Save(ctx context.Context, data *shareddomain.Auth, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterAuth) (err error)
}
