// Code generated by candi v1.18.8.

package shared

import "time"

// Environment additional in this service
type Environment struct {
	// more additional environment with struct tag is environment key example:
	// ExampleHost string `env:"EXAMPLE_HOST"`
	JWTSecret     string        `env:"JWT_SECRET"`
	JWTAccessTTL  time.Duration `env:"JWT_ACCESS_TTL"`
	JWTRefreshTTL time.Duration `env:"JWT_REFRESH_TTL"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
