// Code generated by candi v1.18.8. DO NOT EDIT.

package sdk

import (
	"sync"
)

// Option func type
type Option func(*sdkInstance)

var (
	sdk  SDK
	once sync.Once
)

// SetGlobalSDK constructor with each sdk service option.
func SetGlobalSDK(opts ...Option) {
	s := new(sdkInstance)
	for _, o := range opts {
		o(s)
	}
	once.Do(func() {
		sdk = s
	})
}

// GetSDK get global sdk instance
func GetSDK() SDK {
	return sdk
}

// @candi:construct

// SDK instance abstraction
type SDK interface {
	// @candi:serviceMethod
}

// sdkInstance implementation
type sdkInstance struct {
	// @candi:serviceField
}
