// Code generated by candi v1.18.8. DO NOT EDIT.

package sdk

import (
	"sync"

	// @candi:serviceImport
	"monorepo/sdk/order-service"
)

// Option func type
type Option func(*sdkInstance)

var (
	sdk  SDK
	once sync.Once
)

// SetGlobalSDK constructor with each sdk service option.
func SetGlobalSDK(opts ...Option) {
	s := new(sdkInstance)
	for _, o := range opts {
		o(s)
	}
	once.Do(func() {
		sdk = s
	})
}

// GetSDK get global sdk instance
func GetSDK() SDK {
	return sdk
}

// @candi:construct

// SetOrderservice option func
func SetOrderservice(orderservice orderservice.Orderservice) Option {
	return func(s *sdkInstance) {
		s.orderservice = orderservice
	}
}

// SDK instance abstraction
type SDK interface {
	// @candi:serviceMethod
	Orderservice() orderservice.Orderservice
}

// sdkInstance implementation
type sdkInstance struct {
	// @candi:serviceField
	orderservice	orderservice.Orderservice
}

// @candi:instanceMethod
func (s *sdkInstance) Orderservice() orderservice.Orderservice {
	return s.orderservice
}
