// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"payment-service/internal/modules/provider/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// ProviderRepository abstract interface
type ProviderRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterProvider) ([]shareddomain.PaymentProvider, error)
	Count(ctx context.Context, filter *domain.FilterProvider) int
	Find(ctx context.Context, filter *domain.FilterProvider) (shareddomain.PaymentProvider, error)
	Save(ctx context.Context, data *shareddomain.PaymentProvider, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterProvider) (err error)
}
