// Code generated by candi v1.18.8.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"

	"payment-service/internal/modules/payment/domain"
	"payment-service/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root interfaces.RESTRouter) {
	v1Payment := root.Group(candihelper.V1+"/payment", h.mw.HTTPBasicAuth)

	v1Payment.POST("/checkout/pay", h.createTransaction)
	// root.POST("/payment/notification", h.paymentNotification) // Endpoint untuk notifikasi Midtrans, tanpa auth
}

// createTransaction documentation
// @Summary			Create Payment Transaction
// @Description		API for create a new payment transaction using Midtrans
// @Tags			Payment
// @Accept			json
// @Produce			json
// @Param			body	body	domain.CreateOrderRequest	true	"Create Order Payload"
// @Success			200	{object}	domain.CreateTransactionResponse
// @Success			400	{object}	wrapper.HTTPResponse
// @Success			500	{object}	wrapper.HTTPResponse
// @Security		ApiKeyAuth
// @Router			/v1/payment/checkout [post]
func (h *RestHandler) createTransaction(rw http.ResponseWriter, req *http.Request) {
	trace, ctx := tracer.StartTraceWithContext(req.Context(), "PaymentDeliveryREST:CreateTransaction")
	defer trace.Finish()

	body, _ := io.ReadAll(req.Body)
	if err := h.validator.ValidateDocument("payment/save", body); err != nil { // Menggunakan skema payment/save
		wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(rw)
		return
	}

	var payload domain.CreateOrderRequest
	if err := json.Unmarshal(body, &payload); err != nil {
		wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(rw)
		return
	}

	resp, err := h.uc.Payment().CreateTransaction(ctx, &payload)
	if err != nil {
		wrapper.NewHTTPResponse(http.StatusInternalServerError, err.Error()).JSON(rw)
		return
	}

	wrapper.NewHTTPResponse(http.StatusOK, "Transaction created successfully", resp).JSON(rw)
}

// func (h *RestHandler) paymentNotification(rw http.ResponseWriter, req *http.Request) {
// 	trace, ctx := tracer.StartTraceWithContext(req.Context(), "PaymentDeliveryREST:PaymentNotification")
// 	defer trace.Finish()

// 	var payload map[string]interface{}
// 	if err := json.NewDecoder(req.Body).Decode(&payload); err != nil {
// 		log.Printf("[Webhook] Error parsing body: %v\n", err)
// 		wrapper.NewHTTPResponse(http.StatusBadRequest, "Cannot parse request body").JSON(rw)
// 		return
// 	}

// 	trace.SetTag("order_id", payload["order_id"])
// 	log.Printf("[Webhook] Received notification payload: %+v", payload)

// 	err := h.uc.Payment().ProcessPaymentNotification(ctx, payload)
// 	if err != nil {
// 		// Jika ada error dari usecase (misal: tidak bisa konek ke Midtrans atau DB),
// 		// kembalikan 500 agar Midtrans mencoba mengirim ulang notifikasi.
// 		wrapper.NewHTTPResponse(http.StatusInternalServerError, err.Error()).JSON(rw)
// 		return
// 	}

// 	// WAJIB, agar Midtrans tahu notifikasinya sudah diterima & berhenti mengirim ulang.
// 	wrapper.NewHTTPResponse(http.StatusOK, "ok").JSON(rw)
// }
