// Code generated by candi v1.18.8.

package usecase

import (
	"context"

	"payment-service/internal/modules/category/domain"
	"payment-service/pkg/shared/repository"
	"payment-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// CategoryUsecase abstraction
type CategoryUsecase interface {
	GetAllCategory(ctx context.Context, filter *domain.FilterCategory) (data domain.ResponseCategoryList, err error)
	GetPaymentList(ctx context.Context, filter *domain.FilterCategory) (data domain.ResponseCategoryList, err error)
	GetDetailCategory(ctx context.Context, id int) (data domain.ResponseCategory, err error)
	CreateCategory(ctx context.Context, data *domain.RequestCategory) (res domain.ResponseCategory, err error)
	UpdateCategory(ctx context.Context, data *domain.RequestCategory) (err error)
	DeleteCategory(ctx context.Context, id int) (err error)
}

type categoryUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewCategoryUsecase usecase impl constructor
func NewCategoryUsecase(deps dependency.Dependency) (CategoryUsecase, func(sharedUsecase common.Usecase)) {
	uc := &categoryUsecaseImpl{
		deps:    deps,
		repoSQL: repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),

	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
