// Code generated by candi v1.18.8.

package usecase

import (
	"context"
	"crypto/rsa"

	"monorepo/services/user-service/internal/modules/auth/domain"
	"monorepo/services/user-service/pkg/shared"
	"monorepo/services/user-service/pkg/shared/repository"
	"monorepo/services/user-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
)

// AuthUsecase abstraction
type AuthUsecase interface {
	Login(ctx context.Context, email, password string) (resp domain.ResponseLogin, err error)
	Logout(ctx context.Context, token string) error
	ValidateToken(ctx context.Context, tokenString string) (claim *domain.CustomClaims, err error)
	RefreshToken(ctx context.Context, token, refreshToken string) (resp *domain.ResponseGenerateToken, err error)
}

type authUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	publicKey     *rsa.PublicKey
	privateKey    *rsa.PrivateKey
	env           shared.Environment
	cache         interfaces.Cache
	// repoMongo     repository.RepoMongo
}

// NewAuthUsecase usecase impl constructor
func NewAuthUsecase(deps dependency.Dependency) (AuthUsecase, func(sharedUsecase common.Usecase)) {

	uc := &authUsecaseImpl{
		deps:       deps,
		repoSQL:    repository.GetSharedRepoSQL(),
		publicKey:  deps.GetKey().PublicKey(),
		privateKey: deps.GetKey().PrivateKey(),
		env:        shared.GetEnv(),
		cache:      deps.GetRedisPool().Cache(),
		// repoMongo: repository.GetSharedRepoMongo(),
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
