// Code generated by candi v1.18.8.

package repository

import (
	"context"
	"strings"

	"time"

	"payment-service/internal/modules/method/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"payment-service/pkg/shared"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type methodRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewMethodRepoSQL mongo repo constructor
func NewMethodRepoSQL(readDB, writeDB *gorm.DB) MethodRepository {
	return &methodRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *methodRepoSQL) FetchPaymentList(ctx context.Context, filter *domain.FilterMethod) (data []shareddomain.PaymentProvider, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "CategoryRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterMethod(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *methodRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterMethod) (data []shareddomain.PaymentMethod, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "MethodRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := shared.SetSpanToGorm(ctx, r.readDB).
		Joins("JOIN payment_category ON payment_category.id = payment_method.category_id")

	db = r.setFilterMethod(db, filter).
		Order("payment_category.sequence ASC")

	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset()) // Menambahkan paginasi
	}
	err = db.Find(&data).Error
	return
}

func (r *methodRepoSQL) Count(ctx context.Context, filter *domain.FilterMethod) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "MethodRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterMethod(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.PaymentMethod{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *methodRepoSQL) Find(ctx context.Context, filter *domain.FilterMethod) (result shareddomain.PaymentMethod, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "MethodRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterMethod(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *methodRepoSQL) FindByID(ctx context.Context, id int) (result shareddomain.PaymentMethod, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "MethodRepoSQL:FindByID")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	filter := &domain.FilterMethod{ID: &id}
	err = r.setFilterMethod(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *methodRepoSQL) Save(ctx context.Context, data *shareddomain.PaymentMethod, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "MethodRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = shared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *methodRepoSQL) Delete(ctx context.Context, filter *domain.FilterMethod) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "MethodRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterMethod(shared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.PaymentMethod{}).Error
	return
}

func (r *methodRepoSQL) setFilterMethod(db *gorm.DB, filter *domain.FilterMethod) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("payment_method.id = ?", *filter.ID)
	}
	if filter.Search != "" {
		// Perbaikan: Mengganti 'field' yang ambigu dengan kolom yang spesifik.
		db = db.Where("(payment_method.name ILIKE ? OR payment_method.code ILIKE ?)", "%"+filter.Search+"%", "%"+filter.Search+"%")
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
