// Code generated by candi v1.18.8.

package repository

import (
	"context"

	"payment-service/internal/modules/method/domain"
	shareddomain "payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// MethodRepository abstract interface
type MethodRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterMethod) ([]shareddomain.PaymentMethod, error)
	Count(ctx context.Context, filter *domain.FilterMethod) int
	Find(ctx context.Context, filter *domain.FilterMethod) (shareddomain.PaymentMethod, error)
	Save(ctx context.Context, data *shareddomain.PaymentMethod, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterMethod) (err error)
}
